spring:
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: XXX
        # 命名空间
        namespace: 79883141-087a-4f4f-9a13-f2c42bb73e14
      config:
        enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://XXX:3306/XXX?useUnicode=true&characterEncoding=utf8&useSSL=false&noAccessToProcedureBodies=true&serverTimezone=Asia/Shanghai
    username: XXX
    password: XXX

# 测试环境打印SQL脚本
logging:
  level:
    com.minio.oss: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

minio:
  url: XXX
  access-key: XXX
  secret-key: XXX